### PR TITLE
Update Readme.me

### PR DESCRIPTION
**Pull request by billmdevs**
Fixed some commands that were not working and some errors on the file.

### CODE REVIEW

**Comment by zxiiro** [comment]
Greetings @spiritus72 and thank you for your interest in contributing to this project. This project only mirrors it's artifacts to GitHub, contributions to this project need to go through Gerrit [0] in order to do that you will need to setup your Gerrit account, details on how to do that can be found here [1].

[0] https://git.opendaylight.org/gerrit/#/admin/projects/coe
[1] https://docs.releng.linuxfoundation.org/en/latest/gerrit.html

**Comment by billmdevs** [comment]
Thanks @zxiiro for directing me to the original codebase. I am leveraging this project to use on my work. I just found some errors worth mentioning. I will go to through gerrit as instructed.

**Comment by tykeal** [comment]
Closing PR as @zxiiro metioned, this is a mirror only.

**Comment by billmdevs** [comment]
Hello @zxiiro I don't have push/commits access to your repository from gerrit so I can't do anything from that end.

**Comment by zxiiro** [comment]
@spiritus72 you need to create an account at https://identity.linuxfoundation.org/ then you can use a tool called "git-review" by running "git review" to push the code to Gerrit.

The details are in the link https://docs.releng.linuxfoundation.org/en/latest/gerrit.html mentioned previously. If there is a specific part of the documentation that is confusing to you, please do let us know and we can try to resolve it.

**Comment by billmdevs** [comment]
Thanks @zxiiro . After having done that. I try to push to with git-review tool but I get this error: 

$git review 
/usr/local/lib/python2.7/dist-packages/requests/__init__.py:83: RequestsDependencyWarning: Old version of cryptography ([1, 2, 3]) may cause slowdown.
  warnings.warn(warning, RequestsDependencyWarning)
Could not connect to gerrit.
Enter your gerrit username: spiritus
Trying again with ssh://spiritus@git.opendaylight.org:29418/coe.git
<traceback object at 0x7f9f38f95b00>
We don't know where your gerrit is. Please manually create a remote
named "gerrit" and try again.
Could not connect to gerrit at ssh://spiritus@git.opendaylight.org:29418/coe.git
Traceback (most recent call last):
  File "/usr/bin/git-review", line 10, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/dist-packages/git_review/cmd.py", line 1534, in main
    sys.exit(e.EXIT_CODE)
AttributeError: 'GitReviewException' object has no attribute 'EXIT_CODE'

**Comment by zxiiro** [comment]
@spiritus72 Did you upload your ssh key to https://git.opendaylight.org/gerrit/#/settings/ssh-keys

As for the message about no named "gerrit" you need to run "git review -s" once to set that up but for it to work your SSH key needs to be known to Gerrit via the link above. Hopefully that will get you further.

**Comment by billmdevs** [comment]
@zxiiro Yes I did upload them and I ran "git review -s". I still have the same error message.

**Comment by zxiiro** [comment]
@spiritus72 sorry you're running into these issues. I'm not sure what that error means. I see some other folks ran into https://meganeshkadam.github.io/post/gerrit/ it.

Perhaps SSH port 29418 port is blocked on your network?

I guess another route you could try is to push using https://

    git push https://spiritus@git.opendaylight.org/gerrit/coe.git HEAD:refs/for/master

This will tell git to push HEAD for review against the master branch using the https method. It will ask for your username and password instead of using SSH keys.

Hope this helps,
Thanh

**Comment by billmdevs** [comment]
When following your instructions this is now what it gives me:

$ git push https://spiritus@git.opendaylight.org/gerrit/coe.git HEAD:refs/for/
master
Password for 'https://spiritus@git.opendaylight.org': 
Counting objects: 5, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 588 bytes | 0 bytes/s, done.
Total 5 (delta 3), reused 0 (delta 0)
remote: Resolving deltas: 100% (3/3)
remote: Processing changes: refs: 1, done    
remote: ERROR: [0aa3611] missing Change-Id in commit message footer
remote: 
remote: Hint: To automatically insert Change-Id, install the hook:
remote:   gitdir=$(git rev-parse --git-dir); scp -p -P 29418 spiritus@git.opendaylight.org:hooks/commit-msg ${gitdir}/hooks/
remote: And then amend the commit:
remote:   git commit --amend
remote: 
To https://spiritus@git.opendaylight.org/gerrit/coe.git
 ! [remote rejected] HEAD -> refs/for/master ([0aa3611] missing Change-Id in commit message footer)
error: failed to push some refs to 'https://spiritus@git.opendaylight.org/gerrit/coe.git'

**Comment by zxiiro** [comment]
Right, normally `git review -s` will set that up for you but you can pull it down manually with curl too:

     curl -Lo .git/hooks/commit-msg http://gerrit.linuxfoundation.org/infra/tools/hooks/commit-msg
     chmod +x .git/hooks/commit-msg

Then doing a "git commit --amend -s" and then saving should automatically trigger the hook and inserts the Change-Id. I also suggest passing the "-s" option so that it automatically adds your "Signed-off-by" line as well which is the next thing it will ask you about.

Hope this helps,
Thanh

**Pull request closed without merging**
